export interface AnimeWatchingCreateProps {
  fields: {
    titleEnglish: string;
    titleJapanese: string;
    description: string;
    minsPerEpisode: string;
    episodeCount: string;
    airedFrom: Date;
    airedTo?: Date | undefined | null;
    currentlyAiring: boolean | string;
    imageUrl: string;
  };
}

export interface AnimeSearchProps {
  mal_id: number;
  url: string;
  images: { [key: string]: Image };
  trailer: Trailer;
  title: string;
  title_english: string;
  title_japanese: string;
  title_synonyms: string[];
  type: string;
  source: string;
  episodes: number;
  status: string;
  airing: boolean;
  aired: Aired;
  duration: string;
  rating: string;
  score: number;
  scored_by: number;
  rank: number;
  popularity: number;
  members: number;
  favorites: number;
  synopsis: string;
  background: null;
  season: null;
  year: null;
  broadcast: Broadcast;
  producers: Demographic[];
  licensors: Demographic[];
  studios: Demographic[];
  genres: Demographic[];
  explicit_genres: any[];
  themes: Demographic[];
  demographics: Demographic[];
}

export interface Aired {
  from: Date;
  to: null;
  prop: Prop;
  string: string;
}

export interface Prop {
  from: From;
  to: From;
}

export interface From {
  day: number | null;
  month: number | null;
  year: number | null;
}

export interface Broadcast {
  day: null;
  time: null;
  timezone: null;
  string: null;
}

export interface Demographic {
  mal_id: number;
  type: Type;
  name: string;
  url: string;
}

export enum Type {
  Anime = 'anime',
}

export interface Image {
  image_url: string;
  small_image_url: string;
  large_image_url: string;
}

export interface Trailer {
  youtube_id: string;
  url: string;
  embed_url: string;
  images: Images;
}

export interface Images {
  image_url: string;
  small_image_url: string;
  medium_image_url: string;
  large_image_url: string;
  maximum_image_url: string;
} // Generated by https://quicktype.io

export interface AnimeWatchingProps {
  id: string;
  createdTime: string;
  fields: Fields;
}

export interface Fields {
  titleEnglish: string;
  titleJapanese: string;
  description: string;
  minsPerEpisode: string;
  episodeCount: string;
  airedFrom: string;
  airedTo: string;
  currentlyAiring: string;
  imageUrl: string;
  episodeWatching?: string;
}
